### ISSUE TITLE
Splash Screen Internet Connection

### ISSUE THREAD

**Issue by kemalsami** [Youbaku/Android#15]
Internet connection olmaması durumunda internet olmadığını gösteren bir sayfaya yönlendirilmesi gerekmektedir.

**Comment by alirzayev** [comment]
Bu durum zaten main activtyde kontrol ediliyormuş zaten. Dolayısıyla splashscreen activityde bole bir kontrole gere yok. Uygulama wifi connection check yapmıyordu. Bu durum düzeltildi.
