### ISSUE TITLE
Popular fragment inactive places

### ISSUE THREAD

**Issue by alirzayev** [Youbaku/Android#18]
Popular fragmentinde olan mekanlarda aktiv rate olduğu halde yorumlar gozukmemekte. Bu durum düzeltilecek.

**Comment by alirzayev** [comment]
---10.0/5.0 Problemi---  Popular Place fragmentinde su anda ratleri gosterirken hata var.

**Comment by kemalsami** [comment]
Rating hatası düzeltildi ancak ilk seferde comment sayısı ve distance gözükmemesi hatası düzeltilemedi

**Comment by kemalsami** [comment]
görülmekte ama rengi beyaz olduğundan görülmemekteymiş. Siyah olarak set edince rengini düzeldi.
