### ISSUE TITLE
"Open" ya da "Closed" olarak gösterilen mekanların düzgün bir şekilde belirlenmesi

### ISSUE THREAD

**Issue by kemalcagri67** [Youbaku/Android#37]
Azerbaycan ile Almanya arasındaki saat farkından kaynaklandığı söylenilen, mekan detayında yazan ve bir mekanın "Open" veya "Closed" olmasının bu farklılık gözetilerek düzeltilmesi.

**Comment by kemalsami** [comment]
server tarafında bilgi gelecek şekilde halledildi ... Test edilmesi gerekmektedir
