### ISSUE TITLE
Find Place Subcategory İsimlerin Gelmemesi

### ISSUE THREAD

**Issue by kemalsami** [Youbaku/Android#6]
Subcategory'lerin sayısı doğru gelse de isimleri gelmemektedir. Bazı değerlerin Statik değişkenlerde tutulmaya geçilmesi sırasında oluşan bir hatadır.

**Comment by alirzayev** [comment]
Bu hatanın nedeni fetchSubcategoryList methodunun içerisinde subcategory objesi oluşturarken sub categoriye titlenin set edilmemesidir. Sadece id set ediliyor.
