### ISSUE TITLE
Find Place subcategory hatası

### ISSUE THREAD

**Issue by kemalsami** [Youbaku/Android#7]
Farklı main category'lere ait farklı subcategory'lerin seçilmesi durumunda hata vermektedir. Örneğin "Place as" category'sinden seçilen iki seçenek ardından "Place For" dan bir subcategory ve bir diğer category'den subcategory seçilmesi durumunda ilk seçilenler kaybolmaktadır. (Visible alan dışında kalması durumunda seçili seçenek yine Visible alana gelmesi durumudan özelliğini kaybetmektedir.)

**Comment by alirzayev** [comment]
Genel olarak bu  sorun expandablelistview yapsından dolayıdır. Her expanda ettiği zaman dataları yeniden yükler. ama bu sorunun çözümü vardır. Aşağdakı linkte çözüm anlatılmıştır.

http://www.lalit3686.blogspot.in/2012/06/today-i-am-going-to-show-how-to-deal.html
